openapi: 3.0.0
info:
  title: detect_glare
  version: '1.0'
  description: REST API to manage images for glare detection
  contact:
    email: chris@nacho.fm
tags:
  - name: detect_glare
servers:
  - url: http://0.0.0.0:5000
paths:
  /detect_glare:
    post:
      description: Run a function to determine if given image metadata indicates possibility of direct glare in the associated image.
      summary: Detect glare from image metadata
      security: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageMetadata'
        description: An instance of an ImageMetadata object.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  glare:
                    type: boolean
                    description: Indicates if there is likely glare in the given image metadata.
                required:
                  - glare
components:
  schemas:
    ImageMetadata:
      description: Image metatadata concerning position and orientation of the image
      type: object
      properties:
        lat:
          type: number
          format: float
          minimum: 0
          maximum: 90
        lon:
          type: number
          format: float
          minimum: -180
          maximum: 180
        epoch:
          type: number
        orientation:
          type: number
          format: float
          minimum: -180
          maximum: 180
      required:
        - lat
        - lon
        - epoch
        - orientation
  securitySchemes: {}
